name: Destroy Lambda

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar AWS credenciais via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        run: |
          cd terraform
          terraform init -reconfigure

      - name: Destruir Lambda
        run: |
          cd terraform
          terraform destroy -auto-approve
